"""Add password reset OTP

Revision ID: 264fef88f2e6
Revises: c44f21b7ecb9
Create Date: 2026-09-13 08:50:46.505404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264fef88f2e6'
down_revision = 'c44f21b7ecb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_resets_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('citizen_locations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_citizen_locations_user_id'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizen_locations', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_citizen_locations_user_id'), ['user_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_resets_email'))

    op.drop_table('password_resets')
    # ### end Alembic commands ###
