"""Add permanent risk data history

Revision ID: 5d05436eb456
Revises: 2c64d77000a0
Create Date: 2026-08-30 10:13:38.732925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d05436eb456'
down_revision = '2c64d77000a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('soil_moisture', sa.Float(), nullable=True),
    sa.Column('slope_degree', sa.Float(), nullable=True),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('historical_landslides', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_data_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_data_longitude'), ['longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_data_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_data_risk_level'), ['risk_level'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_data_risk_level'))
        batch_op.drop_index(batch_op.f('ix_risk_data_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_risk_data_longitude'))
        batch_op.drop_index(batch_op.f('ix_risk_data_latitude'))

    op.drop_table('risk_data')
    # ### end Alembic commands ###
