"""Add disaster report verification audit

Revision ID: 5d5d8160e92d
Revises: 79ac2435114c
Create Date: 2026-08-30 09:42:36.647616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5d8160e92d'
down_revision = '79ac2435114c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disaster_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['verified_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disaster_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verified_by')

    # ### end Alembic commands ###
