"""Add disaster reports

Revision ID: 79ac2435114c
Revises: 5f6a2b1332d7
Create Date: 2026-08-30 09:19:29.323564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ac2435114c'
down_revision = '5f6a2b1332d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disaster_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('disaster_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disaster_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disaster_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_reports_disaster_type'), ['disaster_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_reports_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disaster_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disaster_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_disaster_reports_status'))
        batch_op.drop_index(batch_op.f('ix_disaster_reports_disaster_type'))
        batch_op.drop_index(batch_op.f('ix_disaster_reports_created_at'))

    op.drop_table('disaster_reports')
    # ### end Alembic commands ###
